apiVersion: v1
kind: Service
metadata:
   name: billing-api-service
   labels:
    app: billing-service
spec:
  ports:
  - port: 80
    targetPort: 5005
  selector:
    app: billing-service
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: billing-service
spec:
   strategy:
    type: Recreate
   selector:
    matchLabels:
      app: billing-service
   template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - name: billing-service
        image: skannte/billing-service:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: BillingServicePath
          value: /usr/data
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: sqlite-volume
          mountPath: /usr/data
      volumes:
      - name: sqlite-volume
        persistentVolumeClaim:
          claimName: sqlite-pvc
